export const REQUEST_SOURCES = 'REQUEST_SOURCES';
export const RECIEVE_SOURCES = 'RECIEVE_SOURCES';
export const FETCHING_SOURCES_FAIL = 'FETCHING_SOURCES_FAIL';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_SORTBY = 'UPDATE_SORTBY';
